### ISSUE TITLE
Is this the best approach to pass bunch of services as arguments?

### ISSUE THREAD

**Issue by inamvar** [kianooshaz/cleanservice#1]
Hey @kianooshaz, I enjoyed watching your **clean architecture** video  in [YouTube](https://www.youtube.com/watch?v=Qhf5k2cSr-I).  
 In your example code, there is only one service called `accSrv`. what if we have 15 services?  Is this the best approach to pass bunch of services as arguments into  `echo.New()` function? 
 any idea?
 
![image](https://user-images.githubusercontent.com/6972027/144251056-54d49045-5b2f-4639-9a1d-3e204b673dce.png)

**Comment by kianooshaz** [comment]
Hi @inamvar 
I think it's ok in Go to pass a bunch of services as arguments, but if you don't like it, you can create a new structure for argument type with 15 fields for each service
```
echo.New(logger ,&echo.Services{
 Account: accSrv,
 Payment: paySrv,
 Order: orderSrv,
 ...
)
```
